/**
 * 
 */
package Presentacion.FactoriaPresentacion;

/** 
 * Enum of all UI events that trigger Controller actions
 * @author azuri
 */
public enum Evento {
	ALTA_ENTRENADOR,
	BAJA_ENTRENADOR,
	MODIFICAR_ENTRENADOR,
	MOSTRAR_ENTRENADOR,
	MOSTRAR_ENTRENADORES,
	CREAR_SESION,
	ALTA_CLIENTE,
	BAJA_CLIENTE,
	MODIFICAR_CLIENTE,
	ALTA_SALA,
	BAJA_SALA,
	MODIFICAR_SALA,
	MOSTRAR_SALA,
	MOSTRAR_TODAS_SALAS,
	OBTENER_SESIONES_SALA,
	ALTA_SESION,
	BAJA_SESION,
	MODIFICAR_SESION,
	MOSTRAR_SESION,
	MOSTRAR_TODAS_SESIONES,
	MOSTRAR_SALA_SESION,
	MOSTRAR_ENTRENADOR_SESION,
	RES_ALTA_ENTRENADOR_OK,
	RES_ALTA_ENTRENADOR_KO,
	RES_BAJA_ENTRENADOR_OK,
	RES_BAJA_ENTRENADOR_KO,
	RES_MODIFICAR_ENTRENADOR_OK,
	RES_MODIFICAR_ENTRENADOR_KO,
	RES_MOSTRAR_ENTRENADOR_OK,
	RES_MOSTRAR_ENTRENADOR_KO,
	RES_MOSTRAR_ENTRENADORES_OK,
	RES_MOSTRAR_ENTRENADORES_KO,
	RES_CREAR_SESION_OK,
	RES_CREAR_SESION_KO,
	RES_ALTA_CLIENTE_OK,
	RES_ALTA_CLIENTE_KO,
	RES_BAJA_CLIENTE_OK,
	RES_BAJA_CLIENTE_KO,
	RES_MODIFICAR_CLIENTE_OK,
	RES_MODIFICAR_CLIENTE_KO
}
