/**
 * 
 */
package Presentacion.FactoriaPresentacion;

/** 
 * <!-- begin-UML-doc -->
 * <!-- end-UML-doc -->
 * @author azuri
 * @generated "UML a Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
 */
<<<<<<< Updated upstream
public class Evento {
}
=======
public enum Evento {
	ALTA_ENTRENADOR,
	BAJA_ENTRENADOR,
	MODIFICAR_ENTRENADOR,
	MOSTRAR_ENTRENADOR,
	MOSTRAR_ENTRENADORES,
	CREAR_SESION,
	ALTA_CLIENTE,
	BAJA_CLIENTE,
	MODIFICAR_CLIENTE,
	MOSTRAR_CLIENTE,
	MOSTRAR_CLIENTES,
	MOSTRAR_SESIONES_CLIENTE,
	APUNTAR_CLIENTE_SESION,
	DESAPUNTAR_CLIENTE_SESION,
	ALTA_SESION,
	BAJA_SESION,
	MODIFICAR_SESION,
	MOSTRAR_SESION,
	MOSTRAR_TODAS_SESIONES,
	MOSTRAR_SALA_SESION,
	MOSTRAR_ENTRENADOR_SESION,
	RES_ALTA_ENTRENADOR_OK,
	RES_ALTA_ENTRENADOR_KO,
	RES_BAJA_ENTRENADOR_OK,
	RES_BAJA_ENTRENADOR_KO,
	RES_MODIFICAR_ENTRENADOR_OK,
	RES_MODIFICAR_ENTRENADOR_KO,
	RES_MOSTRAR_ENTRENADOR_OK,
	RES_MOSTRAR_ENTRENADOR_KO,
	RES_MOSTRAR_ENTRENADORES_OK,
	RES_MOSTRAR_ENTRENADORES_KO,
	RES_CREAR_SESION_OK,
	RES_CREAR_SESION_KO,
	RES_ALTA_CLIENTE_OK,
	RES_ALTA_CLIENTE_KO,
	RES_BAJA_CLIENTE_OK,
	RES_BAJA_CLIENTE_KO,
	RES_MODIFICAR_CLIENTE_OK,
	RES_MODIFICAR_CLIENTE_KO,
	RES_MOSTRAR_CLIENTE_OK,
	RES_MOSTRAR_CLIENTE_KO,
	RES_MOSTRAR_CLIENTES_OK,
	RES_MOSTRAR_CLIENTES_KO,
	RES_MOSTRAR_SESIONES_CLIENTE_OK,
	RES_MOSTRAR_SESIONES_CLIENTE_KO,
	RES_APUNTAR_CLIENTE_SESION_OK,
	RES_APUNTAR_CLIENTE_SESION_KO,
	RES_DESAPUNTAR_CLIENTE_SESION_OK,
	RES_DESAPUNTAR_CLIENTE_SESION_KO
}
>>>>>>> Stashed changes
